version: '3.8'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
